<a href="https://colab.research.google.com/github/Neerpatel25/python-libraries/blob/main/CB1NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(type(a)) # denote which structure is used list of array etc..
print(a.dtype) # denote type of data in array

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
int64


In [ ]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [ ]:
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
c=np.full((5,5),7)
print(c)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
c=np.eye((4))
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Random matrix
randommatrix=np.random.random((2,3))
print(randommatrix)
print(randommatrix[:,2])#all rows but only 2nd col
#seting values
randommatrix[1,0:3]=1
print(randommatrix)

[[0.2996197  0.09000634 0.75238884]
 [0.06724473 0.22841606 0.37684338]]
[0.75238884 0.37684338]
[[0.2996197  0.09000634 0.75238884]
 [1.         1.         1.        ]]


In [ ]:
#set some rows and cols with constant value
z=np.zeros((3,3))
print(z)
z[1,:]=1 # first row and every columns =1
print(z)
z[:,-1]=7 #every row and last columns=7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [1. 1. 7.]
 [0. 0. 7.]]


In [ ]:
#setting datatype
z=np.zeros((3,3),dtype=np.int64)
print(z.dtype)

int64


In [ ]:
#Mathematical operations
x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
#Matrix Multiplication / dot product

print(np.dot(x,y))

print(x.dot(y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
#Multiplication of two vectors
a = np.array([1,2,3,4,5])
b=  np.array([1,2,3,4,5])
print(np.dot(a,b))


55


In [ ]:
a=[1,2,3,4]
print(sum(a))
x=np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0)) # sum col wise
print(np.sum(x,axis=1)) # sum row wise

10
10
[4 6]
[3 7]


In [ ]:
#stacking of array
a=np.array([1,2,3,4])
b= np.array([4,16,36,64])
print(np.stack((a,b),axis=0))#concate horizonatl
print(np.stack((a,b),axis=1))#concate verticcal

[[ 1  2  3  4]
 [ 4 16 36 64]]
[[ 1  4]
 [ 2 16]
 [ 3 36]
 [ 4 64]]


In [ ]:
#Reshape a Numpy array
a=np.array([[1,2,3,4],[4,16,36,64]]) # 2 rows 4 colums
print(a)
a=a.reshape((4,2)) # reshape 4 rows 2 cols
print(a)
a=a.reshape((4,-1))
print(a)
a=a.reshape((-1,4))
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]
[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]
[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]
[[ 1  2  3  4]
 [ 4 16 36 64]]


In [ ]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:

a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


NUMPY RANDOM MODULE


In [ ]:
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[3 4 2 5 1]


In [ ]:
a=np.random.rand(2,3)
print(a)

[[0.47582131 0.62476397 0.31032241]
 [0.51966244 0.08119041 0.15362961]]


In [ ]:
a=np.random.randn(2,3) # in randn return values from standard normal distribution
print(a)

[[-0.87686534  0.71702922  0.85616972]
 [-0.19981928  0.75419802  0.45805996]]


In [ ]:
#random pick one element from array
ele=np.random.choice([1,4,2,5,6])
print(ele)

5


In [ ]:
#pseduo random generate and repalce same random in each refresh
np.random.seed(1)
ele=np.random.choice([1,4,2,5,6])
print(ele)

**NUMPY MORE FUNCTIONS**

In [ ]:
a= np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [ ]:
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))


0
[1 2 2 0]
[1 0]
7
[7 6 3 4]
[4 7]


In [ ]:
#mean
b=np.array([1,2,3,4,5])
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [ ]:
#median
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [ ]:
#Mean Vs Average
print(np.mean(c))
w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.4
2.066666666666667


In [ ]:
#standard devation
print(np.std(c))

#variance
print(np.var(c))

1.854723699099141
3.4400000000000004
