<a href="https://colab.research.google.com/github/Neerpatel25/python-libraries/blob/main/CB3PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Dataframe- Special object to data in tabular form row & columns

In [ ]:
# we can convert any disctonries intp pandas as data
user_data={
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(1,100,5),
}
print(user_data)

{'MarksA': array([10, 45, 17, 50, 23]), 'MarksB': array([95, 78, 79, 52, 87]), 'MarksC': array([92, 98,  2, 30, 45])}


In [ ]:
#how to create dataframe from disctonaries
df=pd.DataFrame(user_data)
print(df)
print(df.head()) # first five rows
print(df.head(n=3)) #fisrt three rows
print(df.tail()) # last five rows
print(df.tail(n=3))#last three rows
print(df.columns)# columns of dataframe

   MarksA  MarksB  MarksC
0      10      95      92
1      45      78      98
2      17      79       2
3      50      52      30
4      23      87      45
   MarksA  MarksB  MarksC
0      10      95      92
1      45      78      98
2      17      79       2
3      50      52      30
4      23      87      45
   MarksA  MarksB  MarksC
0      10      95      92
1      45      78      98
2      17      79       2
   MarksA  MarksB  MarksC
0      10      95      92
1      45      78      98
2      17      79       2
3      50      52      30
4      23      87      45
   MarksA  MarksB  MarksC
2      17      79       2
3      50      52      30
4      23      87      45
Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [ ]:
df=pd.DataFrame(user_data,dtype='float32')
print(df)

   MarksA  MarksB  MarksC
0    10.0    95.0    92.0
1    45.0    78.0    98.0
2    17.0    79.0     2.0
3    50.0    52.0    30.0
4    23.0    87.0    45.0


In [ ]:
#How yo convert dataframe into scv files
df.to_csv('marks.csv') # made csv file from disctonaries


my_data=pd.read_csv('marks.csv')#read from csv files
print(my_data)

   Unnamed: 0  MarksA  MarksB  MarksC
0           0    10.0    95.0    92.0
1           1    45.0    78.0    98.0
2           2    17.0    79.0     2.0
3           3    50.0    52.0    30.0
4           4    23.0    87.0    45.0


In [ ]:
# if you want drop some columns
my_data=my_data.drop(columns=['Unnamed: 0'])
print(my_data)


   MarksA  MarksB  MarksC
0    10.0    95.0    92.0
1    45.0    78.0    98.0
2    17.0    79.0     2.0
3    50.0    52.0    30.0
4    23.0    87.0    45.0


In [ ]:
# Give statics about data like mean, std, min etc...
my_data.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   29.000000  78.200000  53.400000
std    17.592612  16.177144  41.046315
min    10.000000  52.000000   2.000000
25%    17.000000  78.000000  30.000000
50%    23.000000  79.000000  45.000000
75%    45.000000  87.000000  92.000000
max    50.000000  95.000000  98.000000

In [ ]:
df.iloc[3] # row 3

MarksA    50.0
MarksB    52.0
MarksC    30.0
Name: 3, dtype: float32

In [ ]:
df.iloc[3][1] # row 3 col 1

52.0

In [ ]:
# to get location of any column with name
idx= df.columns.get_loc('MarksB')
df.iloc[3,idx]

52.0

In [ ]:
# you can create list
idx=[df.columns.get_loc('MarksB'),df.columns.get_loc('MarksA')]
print(idx)
df.iloc[3,idx]


[1, 0]


MarksB    52.0
MarksA    50.0
Name: 3, dtype: float32

In [ ]:
df.iloc[:3,idx]

MarksB  MarksA
0    95.0    10.0
1    78.0    45.0
2    79.0    17.0

In [ ]:
# sort your dataframe
my_data=my_data.sort_values(by=['MarksA'],ascending=True)
print(my_data)

   MarksA  MarksB  MarksC
0    10.0    95.0    92.0
2    17.0    79.0     2.0
4    23.0    87.0    45.0
1    45.0    78.0    98.0
3    50.0    52.0    30.0


In [ ]:
my_data=my_data.sort_values(by=['MarksA'],ascending=False)
print(my_data)

   MarksA  MarksB  MarksC
3    50.0    52.0    30.0
1    45.0    78.0    98.0
4    23.0    87.0    45.0
2    17.0    79.0     2.0
0    10.0    95.0    92.0


In [ ]:
my_data=my_data.sort_values(by=['MarksC','MarksA'],ascending=False)
print(my_data)

   MarksA  MarksB  MarksC
1    45.0    78.0    98.0
0    10.0    95.0    92.0
4    23.0    87.0    45.0
3    50.0    52.0    30.0
2    17.0    79.0     2.0


In [ ]:
data_array=my_data.values
print(type(my_data))
print(my_data.shape)
print(data_array)
print(type(data_array))
print(data_array.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)
[[45. 78. 98.]
 [10. 95. 92.]
 [23. 87. 45.]
 [50. 52. 30.]
 [17. 79.  2.]]
<class 'numpy.ndarray'>
(5, 3)


In [ ]:
#Numpy Arrays back into data frame
new_df=pd.DataFrame(data_array,dtype='int32',columns=['physics','chem','maths'])
new_df.to_csv("PCM.csv")
pcm=pd.read_csv("PCM.csv")
print(pcm)

   Unnamed: 0  physics  chem  maths
0           0       45    78     98
1           1       10    95     92
2           2       23    87     45
3           3       50    52     30
4           4       17    79      2


In [ ]:
new_df.to_csv("PCM.csv",index=False)# without columns
pcm=pd.read_csv("PCM.csv")
print(pcm)

   physics  chem  maths
0       45    78     98
1       10    95     92
2       23    87     45
3       50    52     30
4       17    79      2
